Budapest-Quantum-Computing-Group/piquasso

piquasso/_backends/gaussian/state.py
scripts/gbs_hypothesis_test_script.py

We tried to be too smart.
The previous calculation introduced a bias, since it divided the
currently calculated probability by the previously calculated one to
acquire conditional probabilities. This is wrong, since the previous
probability was conditioned on a different heterodyne measurement,
corresponding to a different quantum state.
It hasn't been noticed with the hypothesis test. The issue was noticed
by observing that the set of conditional probabilities didn't always sum
up to one.
The calculation was rewritten to omit the previous probability.
Additionally, the normalization and the previos samples from the
occupation number factorial in the denominator can be omitted, since it
is the same for every "probabilites". Omitting these factors, the
variables got renamed to "weight(s)" …

fix(GaussianState): GBS sampling is biased

---

piquasso/_backends/gaussian/state.py
piquasso/api/constants.py
piquasso/instructions/measurements.py
scripts/threshold_histogram_using_torontonian_script.py
scripts/threshold_hypothesis_test_using_torontonian_script.py
tests/backends/gaussian/test_measurements.py

The `ThresholdMeasurement` can be performed via the GBS algorithm using
the hafnian, too. This is beneficial, since the latter is faster
asymptotically than the algorithm with the torontonian. The algorithm
works by mapping the non-zero results from the GBS samples to 1.
Both calculations are enabled by the `use_torontonian` flag in
`constants`, defaulted to `False`. This is not specified in the
constructor parameter of `ThresholdMeasurement`, since it is specific to
the simulation, but (should be) irrelevant regarding the results.
The `cutoff` optional parameter is added to `ThresholdMeasurement`.
**Notes**:
- The `cutoff` parameter is odd in `ThresholdMeasurement`, while the
`use_torontonian` is technically a global variable. We might want to
rethink this.
- The simulation using the …

feat(GaussianState): Threshold using hafnian

---

piquasso/_backends/fock/general/calculations.py
piquasso/_backends/fock/pure/calculations.py
piquasso/_backends/gaussian/calculations.py
piquasso/_backends/sampling/calculations.py
piquasso/api/computer.py
piquasso/api/result.py
piquasso/api/state.py
tests/api/conftest.py
tests/backends/fock/general/test_measurements.py
tests/backends/fock/pure/test_measurements.py

Generally, the `State` classes should not have any memory regarding
the simulation whatsoever, which makes sense from the perspective of a
user as well.

Removing odd attributes from `State`

---

piquasso/_backends/fock/general/simulator.py
piquasso/_backends/fock/pure/simulator.py
piquasso/_backends/gaussian/simulator.py
piquasso/_backends/sampling/simulator.py
piquasso/api/computer.py
tests/api/conftest.py

The `Simulator._instruction_map` got rewritten to use instruction
classes instead of just string, thereby reducing possible coding errors.

refact(Simulator): Instruction map keys are classes

---

docs/conf.py
piquasso/_backends/fock/general/state.py
piquasso/_backends/fock/pure/state.py
piquasso/_backends/gaussian/state.py
piquasso/api/instruction.py
piquasso/api/mode.py
piquasso/api/program.py
piquasso/api/result.py
piquasso/api/state.py
piquasso/decompositions/clements.py
piquasso/instructions/channels.py
piquasso/instructions/gates.py
piquasso/instructions/measurements.py
piquasso/instructions/preparations.py

The documentation of the constructor parameters is moved to the
`__init__` method, which is concatenated in the documentation by
`sphinx`.
The ordering of classes in the documentation is changed to be the
order in the source code.

doc: Constructor parameter documentation

---

docs/index.rst
docs/instructions/channels.rst
piquasso/__init__.py
piquasso/_backends/gaussian/calculations.py
piquasso/_backends/gaussian/simulator.py
piquasso/_math/linalg.py
piquasso/instructions/channels.py
tests/backends/gaussian/test_channels.py

The `Attenuator` channel has been implemented for the `gaussian`
backend.
The `channels.py` has been added to the documentation.
References:
- **Quantum Continuous Variables** by Alessio Serafini

feat(channels): Attenuator

---

piquasso/_backends/fock/general/calculations.py
piquasso/_backends/fock/general/state.py
piquasso/_backends/fock/pure/calculations.py
piquasso/_backends/fock/pure/state.py
piquasso/_backends/fock/state.py
piquasso/_math/fock.py
tests/backends/fock/general/test_state.py
tests/backends/fock/pure/test_state.py

During the calculation of the `ParticleNumberMeasurement` instruction in
the `fock` backends, the elements of the state vector or density matrix
is cast with `float`. This wouldn't be a problem where all the modes are
measured, but it definitely doesn't work for less modes in general,
because (essentially) the imaginary parts are thrown away.
The algorithm has been rewritten to reduce the state to the measured
modes first, and then calculate the particle number measurement
probabilities corresponding to the reduced state.

fix(fock): Explicit casting of complex coefficients

---

piquasso/_backends/gaussian/calculations.py
tests/backends/gaussian/test_channels.py

The `Attenuator` channel haven't been implemented correctly, since the
matrices `X` and `Y` were not embedded. This has been fixed in this
patch, and a test case has been included.

fix(gaussian): Attenuator channel

---

piquasso/_backends/fock/general/state.py
tests/backends/fock/pure/test_state.py

In the `reduced()` method, the new `FockState` instance didn't inherit
the `_config` attribute, which resulted in errors. This has been fixed
in this patch.

fix(fock): Reduction passes config

---

piquasso/_backends/fock/pure/state.py
tests/backends/fock/pure/test_state.py

A new method called `quadratures_mean` has been implemented in `fock/pure/state.py`.
Test cases has been written accordingly.
This method is needed for the pennylane-piquasso plugin

feat(PureFockState): quadratuers_mean

---

piquasso/api/program.py
tests/api/program/test_code_generation.py

The function `Program.as_code()` produced incorrect code when called on empty programs.
This issue has been fixed and a test has been added.

Fix code generation of empty programs

---

piquasso/_backends/fock/general/state.py
piquasso/_backends/fock/pure/state.py
piquasso/_backends/gaussian/state.py
piquasso/_backends/sampling/state.py
tests/backends/fock/test_gates.py
tests/backends/test_state.py

The method `get_particle_detection_probability` accepted all kinds of
occupation numbers, but gave wrong (complex) results silently. This has
been fixed by raising an error, if the wrong length of occupation
numbers are specified.

fix(_backends): `get_particle_detection_probability`

---

piquasso/_backends/gaussian/calculations.py
piquasso/_math/hermite.py
piquasso/_math/validations.py

There were some problems on Python version 3.8 and above with the
typing, these were corrected in this patch, except for
`modified_hermite_multidim`, where I deleted all the typings. The
solution would be really messy, and type hinting this function is not
very helpful anyway.

fix(typing): Typing errors on 3.8 and above

---

piquasso/_backends/fock/general/calculations.py
piquasso/_backends/fock/pure/calculations.py
piquasso/_backends/gaussian/calculations.py
piquasso/_backends/gaussian/probabilities.py
piquasso/_backends/gaussian/state.py
piquasso/_math/fock.py
piquasso/_math/permanent.py
piquasso/api/config.py
piquasso/api/simulator.py
piquasso/api/state.py
piquasso/api/typing.py
tests/api/conftest.py
tests/api/test_config.py
tests/api/test_simulator.py

Different default configs are needed to be supported, since we might
want to use different parameters in plugins.
The permanent and hafnian calculation functions are moved to `Config` in
order to
1) enable the user to specify it, if needed;
2) enable a plugin to override it.
Tests were written accordingly in `test_config.py`.

Support different configs, Extract permanent + hafnian

---

piquasso/_backends/gaussian/calculations.py
piquasso/_backends/gaussian/state.py
tests/backends/gaussian/test_measurements.py
tests/backends/gaussian/test_state.py

There were 3 instances in the Gaussian backend, where the config is not
properly passed to a new instance of the state. This caused unusual
validation errors due to covariance matrices not adhering to the
Robertson-Schrödinger uncertainty relation, which turned out to be an
issue because the covariance matrices were divided with the default
`hbar` value, instead of the one in the config.
This has been fixed in this patch by passing the config to every
instantiation.
Several test cases were added, which would have failed with the original
code.

fix(gaussian): Config inheritance of states

---

piquasso/_backends/fock/general/calculations.py
piquasso/_backends/fock/pure/calculations.py
piquasso/instructions/gates.py
tests/backends/test_backend_equivalence.py
tests/backends/test_instruction_autoscaling.py

- Now the user can apply the kerr gate to multiple qumodes with
a single instruction.
- Test cases have been added accordingly.

feat(fock) enabling scaling for kerr gate:

---

piquasso/_backends/gaussian/calculations.py
piquasso/_backends/gaussian/probabilities.py
piquasso/_backends/gaussian/state.py
piquasso/_math/hafnian.py
piquasso/api/config.py
piquasso/api/typing.py
scripts/gbs_nondisplaced_histogram_script.py
tests/_math/test_hafnian.py

**1st commit**
The reduction step is moved to the `loop_hafnian_function` in `config`.
**2nd commit**
When the loop hafnian is calculated with no displacement, one could
easily use the regular hafnian function instead, which is implemented in
this patch. The hafnian function could be specified in the config.
A new script has been written testing GBS with no displacement.

feat(config): Moving reduction to loop hafnian + feat(gaussian): Hafnian and loop hafnian cases

---

piquasso/instructions/gates.py

The term "Bogoliubov transformation" can be confusing for naming gates
with up to quadratic Hamiltonians. Also, it would be better to get rid
of vague names from the codebase. The term "Gaussian gate" fits
perfectly.

feat(gates): Rename `*BogoliubovTransformation`

---

docs/tutorials/boson-sampling.ipynb
piquasso/__init__.py
piquasso/_backends/sampling/calculations.py
piquasso/_backends/sampling/simulator.py
piquasso/instructions/measurements.py
tests/backends/sampling/test_gates.py
tests/backends/sampling/test_measurements.py

The `SamplingSimulator`s `Sampling` measurement class is redundant
since it is essentially the same thing as `ParticleNumberMeasurement` in
the other simulator classes. Therefore the `SamplingSimulator` is
rewritten to use `ParticleNumberMeasurement` instead.

feat(measurements): Delete `Sampling`

---

piquasso/__init__.py
piquasso/_backends/sampling/calculations.py
piquasso/_backends/sampling/simulator.py
piquasso/_backends/sampling/state.py
piquasso/_math/validations.py
piquasso/instructions/channels.py
piquasso/instructions/gates.py
tests/backends/sampling/test_gates.py

The channel `TransmissivityMatrix` might be handy if the user wants to
model more general losses in the `SamplingSimulator`. With this one can
specify a general transmissivity matrix, which is essentially equivalent
to a `Loss` channel with two (generally different) `Interferometer`
gates before and after.
Tests have been written. For these, and `__eq__` method is constructed
in `SamplingState`.

feat(sampling): TransmissivityMatrix

---

requirements.txt

Running `black` resulted in the error
```
ImportError: cannot import name '_unicodefun' from 'click'
```
since the most recent release of `click` breaks `black`. However, this
has been fixed in `black==22.3.0`.
Issue: https://github.com/psf/black/issues/2964

fix(requirements.txt): Bumping `black` version

---

piquasso/__init__.py
piquasso/_backends/sampling/calculations.py
piquasso/_backends/sampling/simulator.py
piquasso/instructions/channels.py
tests/backends/sampling/test_gates.py

`TransmissivityMatrix` got renamed to `LossyInterferometer`, since the
latter name is more descriptive regarding its usage.

feat(sampling): Rename `TransmissivityMatrix`

---

requirements.txt
tox.ini

nbmake has been added to the development dependencies to test if the *.ipynb files in docs/ can indeed be executed.
nbqa has been added in order to check *.ipynb files with flake8.
pytest has been updated to install nbmake.
tox.ini has been updated to test *.ipynb files.

Check IPython notebook executability and flake8 tests.

---

benchmarks/purefock_beamsplitter_benchmark.py
benchmarks/purefock_interferometer_benchmark.py

2 benchmarks were written:
- `purefock_beamsplitter_benchmark`: Benchmarks the 2-mode beamsplitter
gate;
- `purefock_interferometer_benchmark`: Benchmarks a general
interferometer.

perf(benchmarks): Additional pure Fock benchmarks

---

piquasso/decompositions/clements.py
tests/decompositions/test_clements.py

During test writing for the Clements decomposition under
`piquasso/decompositions/clements.py`, an issue has been encountered.
Namely, there is a possible zero division error during the
decomposition: one needs to handle the zero division case separately in
the `Clements` class.

FIX(clements): Handling 0 matrix elements

---

piquasso/_backends/fock/general/calculations.py
tests/backends/test_backend_equivalence.py
tests/conftest.py

In the calculation functions for the `FockSimulator`, the auxiliary
modes were passed incorrectly to `embed_matrix`, since the auxiliary
modes were determined from the whole `instruction.modes` instead of just
the loop variable `mode`. This has been fixed.
Equivalence tests have been written accordingly.

fix(FockSimulator): Wrong auxiliary modes in calculation

---

piquasso/_backends/fock/calculations.py
piquasso/_backends/fock/general/simulator.py
piquasso/_backends/fock/general/state.py
piquasso/_backends/fock/pure/simulator.py
piquasso/_backends/fock/state.py
tests/backends/fock/general/test_channels.py
tests/backends/fock/pure/test_channels.py
tests/backends/test_backend_equivalence.py

The support for the `Attenuator` channel for `PureFockSimulator` and
`FockSimulator` has been written in this patch.
The calculation function `attenuator` has been written in a manner that
it works with both simulators, which was easy to achieve since this
channel produces a mixed state (i.e. `FockState`) in general.
Resolves #183

feat(fock): `Attenuator` support

---

piquasso/_backends/fock/general/calculations.py
piquasso/_backends/fock/pure/calculations.py
piquasso/instructions/gates.py
tests/api/utils/test_code_generation.py
tests/backends/test_backend_equivalence.py
tests/backends/test_instruction_autoscaling.py

Some tests were not entirely thorough on the scaling of the `Kerr` and
the `CubicPhase` gates. Additional tests were written, and it turned out
that the `Kerr` gate is not working.
The issue was, that the `kerr` calculation in `FockSimulator` and
`PureFockSimulator` was written in a way that only the first mode was
considered for a multimode calculation. This has been fixed by rewriting
the logic to consider multiple modes.
Several tests were written for testing the scalability of the `Kerr` and
`CubicPhase` gates. Furthermore, the `test_kerr_equivalency` has not
been testing the equivalence between the `FockSimulator` and
`PureFockSimulator`, therefore it has been rewritten to do that.
Additional tests have been written testing the code generation with the
`Kerr` and `CubicPhase` gates.

fix(Kerr): Kerr gate scaling

---

piquasso/__init__.py
piquasso/_backends/calculator.py
piquasso/_backends/fock/pure/calculations.py
piquasso/_backends/fock/pure/simulator.py
piquasso/_backends/fock/pure/state.py
piquasso/_backends/tensorflow/__init__.py
piquasso/_backends/tensorflow/calculator.py
piquasso/_backends/tensorflow/simulator.py
piquasso/_math/decompositions.py
piquasso/_math/fock.py
piquasso/_math/linalg.py
piquasso/_math/permanent.py
piquasso/api/calculator.py
piquasso/api/instruction.py
piquasso/api/simulator.py
piquasso/api/state.py
piquasso/instructions/gates.py
setup.py
tests/_math/test_decompositions.py
tests/api/test_calculator.py
tests/backends/fock/test_gates.py
tests/backends/tensorflow/test_gradient.py
tests/backends/tensorflow/test_simulator.py
tests/backends/test_backend_equivalence.py
tox.ini

A simulator class called `TensorflowPureFockSimulator` has been created,
which supports calculations using Tensorflow.
For this, several calculations had to be rewritten in
`piquasso/_backends/fock/pure/calculations.py`, because in Tensorflow an
`EagerTensor` could not be item assigned. For example, the `squeezing`
and `displacement` calculations had to be rewritten using Python lists.
Also, some modules and functions had to be moved into `BaseCalculator`.
These functions are now implemented in `NumpyCalculator` and in a newly
created `TensorflowCalculator` in a Tensorflow-compatible manner. Most
notably, `numpy` had to be injected, since for Tensorflow calculations
we want to use `tensorflow.experimental.numpy`.
Moreover, the `BaseCalculator` instance had to be injected into some …

feat(fock): `TensorflowPureFockSimulator`

---

CHANGELOG.md
piquasso/__init__.py
piquasso/_backends/sampling/calculations.py
piquasso/instructions/channels.py
setup.py
tests/backends/sampling/test_channels.py

**Problem**
The lossy boson sampling with uniform losses produced only zero-array
samples.
**Solution**
It turned out, that the class
`GeneralizedCliffordsUniformLossesSimulationStrategy` has an optional
parameter `transmissivity` and Piquasso is supposed to specify that
parameter.
Some tests have been written testing the singular values of the
interferometer after specifying loss.
The documentation of `pq.Loss` was also unclear about the purpose of
`transmissivity`, it has also been updated.

fix(sampling): Photon detection with uniform loss

---

requirements.txt

The pipeline run resulted in the following error:
```
AttributeError: 'EntryPoints' object has no attribute 'get'
```
It is because `flake8==4.0.1` might used a deprecated endpoint of `importlib_metadata`. Therefore it has been upgraded.
Source:
- https://importlib-metadata.readthedocs.io/en/latest/history.html

dev(requirements): `flake8` upgrade

---

piquasso/_backends/fock/general/calculations.py
piquasso/_backends/fock/pure/calculations.py
piquasso/core/_mixins.py
piquasso/instructions/gates.py

The class `_ScalableFockGates` got deleted, since this class should not exist. The two subclasses `CubicPhase` and `Kerr` have different parameters, and the current logic inserted e.g. a redundant `"gamma": None` entry in the `Kerr._extra_params`.
Instead, the logic has been separated to the two subclasses `CubicPhase` and `Kerr`.
Also, it is very confusing that there is two `"gamma"` and `"xi"` keys in `CubicPhase` and `Kerr` respectively, precisely one in the `_params` and one in the `_extra_params` attribute. The one in the `_extra_params` attribute got a `_vector` suffix to avoid ambiguity.

refact(gates): Delete `_ScalableFockGates`

---

piquasso/_backends/calculator.py
piquasso/_backends/tensorflow/calculator.py
piquasso/_math/fock.py
piquasso/api/calculator.py
tests/api/test_calculator.py

The `to_dense` method in `TensorflowCalculator` has been rewritten to use `tensorflow.scatter_nd`, since it is faster than basic Python indexing.
The method name got updated to `scatter` and the arguments got updated accordingly.
`NumpyCalculator.to_dense` has been updated similarly. There I couldn't find an exact counterpart to `tensorflow.scatter_nd`, but it is solved with some smart indexing.

perf(tensorflow): `scatter`

---

benchmarks/purefock_beamsplitter_increasing_cutoff_benchmark.py
benchmarks/purefock_beamsplitter_increasing_modes_benchmark.py
benchmarks/purefock_clements_interferometer_comparison_benchmark.py
benchmarks/purefock_interferometer_increasing_modes_benchmark.py
piquasso/_backends/fock/pure/calculations.py
piquasso/_math/indices.py
tests/_math/test_indices.py

Previously, the interferometer matrix on the Fock space was calculated using permanents. However, it is faster to calculate it using a recursion rule cited, therefore it has been reimplemented.
Benchmarks have been written testing against Xanadu's Strawberryfields and against Clements decompositing the interferometer.
Sources:
- [Fast optimization of parametrized quantum optical circuits](https://quantum-journal.org/papers/q-2020-11-30-366/)

perf(fock): Recursion rule for interferometer

---

docs/conf.py
docs/index.rst
docs/simulators/tensorflow.rst
docs/tutorials/pure-fock-tensorflow.ipynb
piquasso/_backends/fock/pure/simulator.py
piquasso/_backends/tensorflow/simulator.py

A docstring has been written for `TensorflowPureFockSimulator` and is included in the documentation.
The copyright and some typos got fixed.
A tutorial for `TensorflowPureFockSimulator` has also been written

docs: `TensorflowPureFockSimulator`

---

piquasso/_backends/gaussian/state.py
tests/backends/test_backend_equivalence.py

**Problem**
The `GaussianState.fidelity` method could return values larger than 1 for modes greater than 1.
**Solution**
The fidelity calculation got reimplemented.
During implementation, a different set of equations got used for efficiency.
More tests have been written testing multimode states and mixed states as well.
Sources:
- [Quantum fidelity for arbitrary Gaussian states](https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.115.260501)

FIX(gaussian): Fix fidelity calculation

---

CHANGELOG.md
piquasso/__init__.py
piquasso/_backends/gaussian/state.py
setup.py
tests/backends/test_backend_equivalence.py

**Problem**
The `GaussianState.fidelity` method could return values larger than 1 for modes
greater than 1.
**Solution**
The fidelity calculation got reimplemented.
During implementation, a different set of equations got used for efficiency.
More tests have been written testing multimode states and mixed states as well.
Sources:
- [Quantum fidelity for arbitrary Gaussian states](https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.115.260501)

FIX(gaussian): Fix fidelity calculation on 2.0

---

requirements.txt

`mypy` version is set to 0.981, since for Python 3.10.7 `mypy` and `numpy`
together yields the following error:
```
.tox/py310/lib/python3.10/site-packages/numpy/__init__.pyi:638: error:
Positional-only parameters are only supported in Python 3.8 and greater
```
Source:
- https://github.com/python/mypy/issues/13627

dev(requirements.txt): Freezing mypy version

---

piquasso/_math/decompositions.py
tests/_math/test_decompositions.py

**Problem**
Sometimes scipy.linalg.sqrtm returns complex matrices even when real matrices with
positive eigenvalues got specified. This test specifies a matrix for which the
square root turns out to be complex even if it is real and positive definite.
When a complex matrix is specified to the schur algorithm, automatically the complex
schur algorithm is executed instead of the desired real schur algorithm.
**Solution**
The result is cast to real after the square root.
A test has been added for a specific matrix.

FIX(decompositions): Williamson dtype fix

---

piquasso/_backends/fock/general/state.py
piquasso/_backends/fock/pure/calculations.py
piquasso/_backends/fock/pure/state.py
piquasso/_backends/fock/state.py
piquasso/_backends/gaussian/state.py
piquasso/_backends/sampling/state.py
piquasso/_math/fock.py
piquasso/api/config.py
piquasso/api/instruction.py
piquasso/api/simulator.py
piquasso/instructions/gates.py

The current version of `black` threw the following error:
```
piquasso/_math/fock.py:465: error: Incompatible default for argument "d" (default has type "None", argument has type "int")  [assignment]
piquasso/_math/fock.py:465: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
piquasso/_math/fock.py:465: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
```
The error message speaks for itself, so the required changes were made in the codebase.

chore: MyPy requires `Optional` for `None` default

---

benchmarks/purefock_beamsplitter_increasing_cutoff_benchmark.py
piquasso/_backends/fock/pure/calculations.py

**Problem**
When applying a passive linear gate to a pure Fock state in `PureFockSimulator`, a lot of redundant calculations may happen, since this is the same algorithm used for more general, active linear gates.
**Solution**
`_apply_subspace_matrix_to_state` got separated into 2 functions:
- `_apply_passive_gate_matrix_to_state`: Applies a passive linear gate matrix to the state. It is written considering that the gate matrix is a block diagonal matrix, so it works with the blocks only. This avoids factoring in the off-diagonal zeros, which happened previously. Note, that in this algorithm one iterates over the auxiliary Fock space (where the gate is not applied) instead of the full Fock space, because it turned out that iterating over all the elements in the state vectors are not …

perf(fock/pure): Faster linear gate application

---

benchmarks/purefock_beamsplitter_increasing_cutoff_benchmark.py
benchmarks/purefock_general_benchmark.py
benchmarks/tf_general_benchmark.py

The benchmark `purefock_beamsplitter_increasing_cutoff_benchmark.py` is not a realistic scenario, since only one squeezing is applied, and most beamsplitters after that do nothing. Instead, an occupation number has been prepared.
Moreover, a benchmark has been created testing displacement, squeezing, interferometer and kerr together in `purefock_general_benchmark.py`.

test(benchmarks): PureFockSimulator benchmarks

---

piquasso/_backends/fock/general/state.py
piquasso/_backends/fock/pure/state.py
piquasso/_math/fock.py
piquasso/_math/gate_matrices.py
piquasso/_math/gradients.py
tests/backends/tensorflow/test_gradient.py

**Problem**
The squeezing gradient calculation was slow because the computational
graph contained too much nodes. This could be reduced by defining a
custom gradient.
For testing Squeezing with phaseshifting gradient the `quadratures_mean_variance` needed to be compatible with Tensorflow as well.
Additionally a possible bug in Tensorflow arose regarding the `tf.Variable` `dtype`
**Partial solution**
The custom gradient for the single mode squeezing matrix got defined.
For the phaseshift gradient we must take its conjugate when multiplying with the upstream due to Tensorflow implementations.
For `quadratures_mean_variance` the solution was to rewrite the density matrix to a list form.
The `dtype` error is currently resolved by casting the gradient to `float32` at the end of …

perf(tensorflow): Custom gradient for squeezing

---

piquasso/_math/gradients.py
tests/backends/tensorflow/test_gradient.py

The parameter `phi` of the displacement gate induces a complex gate
matrix and complex gradient and tensorflow requires the gradient to be
conjugated when applied to the stream.
This has been solved and corresponding test has been made.
**Sources**
https://stackoverflow.com/questions/42479024/how-tensorflow-handles-complex-gradient

FIX(tensorflow): Displacement gradient conjugation

---

piquasso/_backends/fock/pure/calculations.py
piquasso/_backends/fock/state.py

**Problem**
Applying an active linear gate to a pure Fock state vector is costly. It would be a bit faster, if some operations could be done at once, since numpy is generally faster that Python for loops.
**Solution**
1. Since this function is only used for single mode gate matrices, the `modes` parameter got rewritten to `mode`, and the logic is simplified accordingly. The `auxiliary_subspace` got refactored into `BaseFockState`, since it is costly to generate all the occupation numbers for each single-mode gate in the circuit.
2. The occupation numbers got divided into sectors corresponding to different particle numbers. This way, the state vector and matrix can be multiplied at once for each of these sectors, provided that one calculates the correct indices for that (contained in …

perf(purefock): Active linear gate multiplication

---

piquasso/instructions/gates.py
tests/backends/tensorflow/test_gates.py

**Problem**
For the interferometer gate when one specified a numpy array as a parameter and the tensorflow backend is used then casting to `tensorflow.EagerTensor` did not happen, resulting in error.
**Solution**
A `_postprocess` method has been written for the `_GaussianGate`.

FIX(tensorflow): Array conversion

---

setup.py

The package `quantum-blackbird==0.3.0` and `numpy` with versions `1.24.*` are incompatible. To fix this, the version of `quantum-blackbird` in `setup.py` has been bumped to `0.5.0`.

FIX(setup.py): Bumping Blackbird version

---

piquasso/_backends/fock/pure/state.py

After the `Vacuum` instruction, the initial state is inititalized without `dtype` parameter, so it defaulted to `float64`. It haven't caused any errors, because it only happened when a passive gate is applied to a vacuum, which leaves the vacuum invariant, and for active gates it is cast to complex. Still, it is technically incorrect.

FIX(fock/pure): State vector dtype fix

---

piquasso/_backends/fock/general/state.py
piquasso/_backends/fock/pure/calculations.py
piquasso/_backends/fock/pure/state.py
piquasso/_backends/fock/state.py
piquasso/_backends/gaussian/calculations.py
piquasso/_backends/gaussian/state.py
piquasso/_backends/sampling/calculations.py
piquasso/_backends/sampling/state.py
piquasso/_math/fock.py
piquasso/_math/gate_matrices.py
piquasso/_math/gradients.py
piquasso/_math/hafnian.py
piquasso/api/config.py
piquasso/instructions/channels.py
piquasso/instructions/gates.py
tests/api/test_config.py
tests/api/utils/test_code_generation.py

**Problem**
During the simulation `dtype` values were explicitly hard-coded into
certain functions. This could lead to inconsistency, hinders debugging 
and lead to distorted comparisons with Strawberry Fields.
**Solution**
Now the `Config` class has a `dtype` member variable which can have one of
the following values: `np.float32` or `np.float64`. Based on this a
complex `dtype` can be mapped as `np.float32 -> np.complex64` and
`np.float64 -> np.complex128`. For this, a `complex_dtype` property was
added as well.
These values are now propagated to most other calculations as well.

feat(config): `dtype` Universality in `Config` class

---

tests/backends/fock/pure/test_state.py
tests/backends/tensorflow/test_gradient.py

The changes in commit `d86a0e8eed77cf26299eaf28c0469c319021f762` are not followed up in the commit `430d8be94a54b36fbf4788d8af0c4d847c1bb773`, unfortunately.

fix(tests): Displacement parameter followup

---

piquasso/_backends/fock/general/state.py
piquasso/_backends/fock/pure/state.py
piquasso/api/config.py
tests/backends/fock/pure/test_state.py

Sometimes normalizing the state vector or density matrix is costly to do after every gate, so a boolean config variable called `normalize` has been provided to disable it.

feat(Config): Ability to disable normalization

---

piquasso/_math/fock.py
piquasso/_math/gradients.py

The matrix gradient calculations were improved by decreasing Python calls during the calculation and by casting the tensorflow upstream differential when possible.

perf(gradients): Matrix gradients performance

---

piquasso/_backends/fock/pure/calculations.py
piquasso/_backends/fock/state.py
tests/backends/test_backend_equivalence.py

Calculating the subspaces (the indices, essentially) is a costly calculation, and it is beneficial to have them stored in a cache for later purposes.

perf(fock): Caching subspaces

---

piquasso/_backends/fock/pure/calculations.py
tests/backends/tensorflow/test_gradient.py

Simply put, when multiplying a vector with a fix matrix as `M @ v`, its jacobian by `v` is just `M`, but in the forward pass, we have to return `M.T @ upstream` in the custom gradient, but `M @ upstream` has been calculated (if `M`, `v` would be real). The fix amounts to rewriting an einsum string. When calculating the gradient of active transformations, this has been done correctly.

FIX(tensorflow): Passive linear gradient error

---

piquasso/_backends/calculator.py
piquasso/_backends/fock/pure/state.py
piquasso/_backends/tensorflow/calculator.py
piquasso/_math/fock.py
piquasso/api/calculator.py
tests/api/test_calculator.py
tests/backends/fock/pure/test_state.py

`PureFockSimulator` calculates with a global cutoff (i.e., cutoff in the total number of particles), therefore it does not represent the state vector as a tensor. `get_tensor_representation` is created to reshape the current state vector representation into a tensor.

feat(fock/pure): `get_tensor_representation`

---

piquasso/_math/gradients.py

The gradient of the squeezing gate by the amplitude of the squeezing parameter has been cast to `float32`, but it is not needed anymore. It may have been needed due to a type promotion we missed, but it seems that this issue has been resolved now by `207d1f3b3aa28e0b13d1d85c3f5b5d2005f90245`.

fix(gradients): Gradient floating point precision

---

benchmarks/tf_cvnn_benchmark.py
docs/index.rst
docs/misc/cvqnn.rst
piquasso/api/exceptions.py
piquasso/cvqnn.py
tests/test_cvqnn.py

A module has been written to support CVQNN-related computations. `tf_cvnn_benchmark.py` has been rewritten using this module.

feat(cvqnn): CVQNN module

---

piquasso/api/instruction.py
tests/instructions/test_str.py

Printing of some instructions yields an error, because `Instruction.__init__` has not been called. This can be resolved by adding this call, or alternatively by fixing `Instruction.__repr__`, which is a more forgiving solution.
Note, that deleting `Vacuum.__init__` for example is not a solution, since we want to avoid the possibility for users to pass parameters directly in `Instruction.__init__`.
Some tests have been written testing the string representation of some instructions.

fix: Printing of instructions

---

piquasso/__init__.py
piquasso/core/_blackbird.py
piquasso/cvqnn.py
tests/test_cvqnn.py

In several cases, the CVQNN layers are needed as a subprogram. Moreover, the `cvqnn` module has been included in `piquasso/__init__.py`. Regarding this, a circular import issue has been resolved in `_blackbird.py`.

feat(cvqnn): `create_layers`

---

benchmarks/purefock_interferometer_increasing_modes_benchmark.py
piquasso/_backends/calculator.py
piquasso/_backends/fock/calculations.py
piquasso/_backends/fock/general/calculations.py
piquasso/_backends/fock/general/state.py
piquasso/_backends/fock/pure/batch_state.py
piquasso/_backends/fock/pure/calculations/__init__.py
piquasso/_backends/fock/pure/calculations/passive_linear.py
piquasso/_backends/fock/pure/state.py
piquasso/_backends/fock/state.py
piquasso/_backends/gaussian/calculations.py
piquasso/_backends/gaussian/probabilities.py
piquasso/_backends/gaussian/state.py
piquasso/_backends/sampling/state.py
piquasso/_math/combinatorics.py
piquasso/_math/decompositions.py
piquasso/_math/fock.py
piquasso/_math/indices.py
piquasso/api/calculator.py
piquasso/api/state.py
tests/api/conftest.py

**Problem**
The logic around `piquasso._math.fock` was quite a bit difficult.
1. The `FockSpace`, `FockBasis`, `FockOperatorBasis` classes overloaded builtin types, which were, frankly, quite unnecessary.
2. The `FockSpace` object is responsible for storing the occupation numbers, in an order which prescribes the ordering of the state vector or the density matrix. However, since calculations depend on `BaseCalculator` and `Config` objects, it was convenient to store these as attributes. This made copying this object a bit involved.
3. Creating a `FockSpace` can be expensive, therefore a caching has been implemented in `BaseFockState`, but this would be unnecessary if one would refactor `FockSpace` into a function and decorate it with `lru_cache`.
4. `FockSpace` is just a tuple of tuples …

feat!(fock): Refactor `FockSpace`

---

benchmarks/tf_1_mode_cvnn_benchmark.py
piquasso/_backends/calculator.py
piquasso/_backends/fock/calculations.py
piquasso/_backends/fock/general/calculations.py
piquasso/_backends/fock/pure/calculations/__init__.py
piquasso/_backends/fock/pure/calculations/passive_linear.py
piquasso/_math/fock.py
piquasso/_math/gate_matrices.py
piquasso/_math/linalg.py
piquasso/api/calculator.py
scripts/cvnn_mean_position_benchmark.py
scripts/cvnn_state_learning_benchmark.py
tests/api/test_calculator.py
tests/backends/fock/test_gates.py
tests/backends/tensorflow/test_batch_gradient.py
tests/backends/test_backend_equivalence.py
tests/slow/test_tf_function.py

`tf.function` requires Piquasso to use Tensorflow's NumPy API in the forward
pass. By default, we use regular NumPy for performance reasons, but this patch
enables users to run Piquasso inside `tf.function`, which might be faster with
JIT compilation enabled. JIT compilation takes some time though, but the
compiled function is an order of magnitude faster than the original function
decorated with `tf.function` only.
In order to enable Piquasso to use `tf.function` the possibility of avoiding
the custom gradient calculations had to be implemented, which is implemented
through `calculator._custom_gradient_enabled`. In the calculations where the
gradient has been replaced by a custom one, a different numpy
(`calculator.forward_pass_np`) needs to be used, and its value depends on …

feat(tensorflow): Enabling `tf.function`

---

piquasso/__init__.py
piquasso/_backends/calculator.py
piquasso/_backends/fock/pure/simulator.py
piquasso/_math/decompositions.py
scripts/jax_cvnn_benchmark.py
setup.py
tests/backends/fock/pure/test_state.py
tests/backends/fock/test_gates.py
tests/backends/fock/test_jax_calculator.py
tests/backends/test_backend_equivalence.py
tests/slow/test_jax_jit_compilation.py
tox.ini

Because JAX has a NumPy API, supporting JAX is not that difficult, and it has been done in this patch.
Unfortunately, the JIT compilation is still very slow, and we may need to reduce the number of Python control flows during the calculation in the future.

feat(JaxCalculator): Supporting JAX in `PureFockSimulator`

---

piquasso/_backends/fock/pure/state.py
tests/slow/test_tf_function.py

**Problem**
When an initial state is specified for `Simulator.execute` and `tf.function` is used, Piquasso throws an error, because the specified initial state is deep-copied, and TensorFlow variables cannot be copied like this.
**Solution**
A `PureFockState.copy` method has been written, which copies explicitely the state vector using the NumPy API of TensorFlow.

fix(tensorflow): Executing with initial state

---

piquasso/_backends/gaussian/calculations.py
tests/backends/gaussian/test_measurements.py

`_get_particle_number_choice` did not generate samples from the NumPy RNG, so if the user does not seed NumPy, the samples will not be reproducible. To fix this, choices in `_get_particle_number_choice` needs to be generated from the RNG from the config.

FIX(gaussian): Random number generation from RNG

---

piquasso/api/simulator.py
tests/api/test_simulator.py

The error message was not properly formatted when invalid instruction is specified.

fix(simulator): Minor error message fix

---

piquasso/_backends/fock/general/state.py
piquasso/_backends/fock/pure/state.py

`nonzero_elements` has been rewritten to use `np.nonzero`, because it is more efficient this way.

refact(fock): `(Pure)FockState.nonzero_elements`

---

piquasso/_backends/fock/pure/calculations/__init__.py
piquasso/_backends/fock/pure/calculations/misc.py
piquasso/_backends/fock/pure/calculations/utils.py
tests/backends/tensorflow/test_gates.py

The `PostSelectPhotons` instruction is made differentiable by using the NumPy API in `calculator`.

feat(fock): Making `PostSelectPhotons` differentiable

---

piquasso/_backends/calculator.py
piquasso/_backends/sampling/calculations.py
piquasso/_backends/sampling/simulator.py
piquasso/_backends/sampling/state.py
piquasso/_backends/sampling/utils.py
piquasso/_math/jax/permanent.py
piquasso/_math/linalg.py
tests/backends/sampling/test_gates.py
tests/backends/sampling/test_jax_gradient.py
tests/backends/test_backend_gradient_equivalence.py

A partial JAX support in `SamplingSimulator` has been enabled. For this, the permanent is implemented in JAX. The same algorithm could not be implemented as in `piquasso._math.permanent`, since JIT compilation in XLA does not handle dynamic shapes which depend on non-static values, e.g., row or column repetitions. Therefore, the permanent is needed to be reduced before calculating the permanent with the Glynn algorithm using Gray codes is implemented.
Moreover, the method `assym_reduce` has been rewritten, which produces the reduced (or scattering) matrix.
The gradient of some attributes of `SamplingState` also works, and is tested in `sampling/test_jax_gradient.py` and `test_backend_gradient_equivalence.py`.

feat(sampling): Partial JAX support

---

piquasso/_backends/sampling/calculations.py
piquasso/_backends/sampling/state.py
tests/backends/sampling/test_gates.py
tests/backends/sampling/test_preparations.py

`SamplingState.initial_state` is made private, since:
- It will not make sense when combinations of Fock basis vectors will be supported;
- It is not really useful to keep it public anyway.
Similar can be said about the `particle_number` attribute, which is just the sum of `initial_state`. Hence, the attributes `particle_number` and `initial_state` got deleted.

refactor!(sampling): Delete unused attributes

---

piquasso/_backends/sampling/state.py
piquasso/_backends/sampling/utils.py
tests/backends/sampling/test_preparations.py

The method `get_particle_detection_probability` was very inefficient, since it calculated the whole distribution for no reason. This has been fixed by defining a `calculate_probability` method in `utils`.

perf(sampling): Faster `get_particle_detection_probability`

---

piquasso/_backends/fock/pure/calculations/measurements.py

There was an error at the density matrix calculation in `ImperfectPostSelectPhotons`, namely, that the conjugation is needed to be done in the second argument in `np.outer`. This way, the resulting density matrix was conjugated.

FIX(fock): `ImperfectPostSelectPhotons` density matrix

---

piquasso/api/result.py

When `TypeVar` is used, the VS code Python extension could not infer that `result.state` is a state, and did not give attribute hints. This can be solved by dropping `TypeVar`.

feat(api): Delete complicated typing of `Result`

---

benchmarks/purefock_clements_interferometer_comparison_benchmark.py
piquasso/_backends/calculator.py
piquasso/api/calculator.py
piquasso/decompositions/clements.py
tests/decompositions/test_clements.py

The Clements decomposition in Piquasso is a bit hard to use in some cases. It is not differentiable, and the datatypes in it are not trivial, it takes time to wrap one's head around it.
For variational circuits, it would be beneficial to support calculating weights from interferometer matrices and to make this decomposition differentiable. These features have been enabled in this patch.

feat!(clements): Rewrite Clements decomposition

---

scripts/train_cz_gate_with_imperfect_detectors.py

A training script has been implemented to train a six mode KLM CZ gate on dual-rail encoded qubits with imperfect postselection to increase the ouput fidelity

script: Train a CZ gate with imperfect postselection

---

piquasso/_backends/fock/general/state.py

Reduction or partial trace is computationally expensive, therefore we might not want to do it in trivial cases. When the `modes` parameter of `reduced` corresponds to all modes, then the reduction should yield the same state. This edge case is added in this patch.

perf(fock): Reduction edge cases

---

piquasso/api/config.py
tests/api/test_config.py

When the user copies a config, it is beneficial to use the original RNG, since otherwise the RNG would reinitialize with the same seed in, e.g., a for loop.

refact!(config): Preserving RNG when copying `Config`

---

piquasso/cvqnn.py
tests/test_cvqnn.py

A function called `get_cvqnn_weight_indices` has been created, which enables slicing of the weights when needed.
Moreover, custom RNG support has been added for reproducability.

feat(cvqnn): `get_cvqnn_weight_indices` + RNG

---

piquasso/cvqnn.py
tests/test_cvqnn.py

There has been a typo in commit `b6833d8`: the function `_get_number_of_single_layer_parameters` returned incorrect results for 1 mode, which is basically an edge case, and should be handled by `_get_number_of_interferometer_parameters`.

FIX(cvqnn): Fix `get_cvqnn_weight_indices`

---

piquasso/_backends/fock/pure/calculations/homodyne.py
piquasso/instructions/gates.py
tests/backends/fock/pure/test_measurements.py

The `config.hbar` value was previously not accounted for in `HomodyneMeasurement`. Moreover, when pre-calculating the partial traces of the density matrices, the whole density matrix was used instead of the reduced one.
These issues have been fixed in this patch.

FIX(fock): `config.hbar` + reduction in `HomodyneMeasruement`

---

piquasso/_backends/gaussian/state.py
tests/backends/gaussian/test_state.py
tests/backends/test_backend_equivalence.py

The calculation for `variance_photon_number` was incorrect on multiple modes, and it has been fixed.

FIX(gaussian): Fix `variance_photon_number`

---

piquasso/_backends/calculators/jax_/calculator.py
piquasso/_backends/calculators/numpy_/calculator.py
piquasso/_backends/gaussian/calculations.py
piquasso/_backends/gaussian/simulator.py
piquasso/_backends/gaussian/state.py
piquasso/_math/decompositions.py
piquasso/api/calculator.py
tests/_math/test_decompositions.py
tests/backends/gaussian/test_gradient.py

A partial support for JAX has been implemented in `GaussianSimulator`.
Note, that calculations needing the (loop)hafnian is not differentiable (yet).

feat(gaussian): JAX support for `GaussianSimulator`

---

.codecov.yml
piquasso/_backends/fock/calculations.py
piquasso/_backends/fock/general/calculations.py
piquasso/_backends/fock/pure/calculations/passive_linear.py
piquasso/_math/combinatorics.py
piquasso/_math/fock.py
piquasso/_math/indices.py
piquasso/_math/permanent.py

Several functions have been rewritten so that they can be compiled using Numba JIT. This is a partial milestone and more functions are planned to be rewritten in this manner.
Specifically, the following changes occurred:
- The `comb` function is now part of the `combinatorics.py` module, and an additional `arr_comb` is implemented accepting and returning arrays. 
- `partitions` is now also jitted alongside `nb_combinations`, equivalent to `itertools.combinations` which is used in many places, hence the different name with the `nb_` prefix. 
- The function `get_fock_space_basis` has also a new implementation with a `nb_` prefix denoting the jitted version. The distinction is necessary due to the extensive use of LRU caching at other parts of the code.
- The function …

perf(fock): jitted `calculate_interferometer_helper_indices`

---

piquasso/_backends/calculators/numpy_/calculator.py

The scipy `sqrtm` returns `complex256` instead of `complex128`, which is also mentioned here: https://github.com/scipy/scipy/issues/18250
To avoid typing errors, the output of `sqrtm` is explicitely cast to `complex128`.

fix(calculator): `sqrtm` return type

---

piquasso/_backends/calculators/calculator.py
piquasso/_backends/fock/calculations.py
piquasso/_backends/fock/general/calculations.py
piquasso/_backends/fock/pure/calculations/passive_linear.py
piquasso/api/calculator.py

The function `calculate_interferometer_on_fock_space` is refactored such that it is part of the `BuiltinCalculator` class as a preparation to make it jit compiled in the future.

refact(fock): Moving `calculate_interferometer_on_fock_space`

---

README.md

The Piquasso logo is not loaded in PyPI when the image is loaded from file, so it is loaded from its GitHub URL instead.

fix(README.md): Piquasso logo

---

tests/test_cvqnn.py

The test `test_create_layers_yields_valid_program` is flaky since commit f3023f343b2ed642f4b8936f5d338d8026356f84, since the state is not automatically normalized after applying active gates, making this test flaky. To remedy this situation, the Fock space cutoff is increased.

chore(tests): Fix flaky test in `test_cvqnn.py`

---

.codecov.yml
piquasso/_backends/calculators/calculator.py
piquasso/_backends/calculators/numpy_/calculator.py
piquasso/_backends/calculators/numpy_/interferometer.py
piquasso/_backends/fock/general/calculations.py
piquasso/_backends/fock/pure/calculations/passive_linear.py

Calculating the unitary matrix corresponding to an interferometer is rewritten to be `numba.njit`-compatible. For this, the `helper_indices` dict is rewritten to be a tuple for compatibility.
The Numba implementation has been drastically modified compared to the Numpy implementation to increase performance. This is because using Numpy one wants to avoid, e.g., Python for loops, whereas in the JIT-compiled Numba code it is more efficient to use explicit for loops.

perf(fock): Interferometer on Fock space JITted

---

piquasso/_backends/gaussian/calculations.py
tests/backends/gaussian/test_measurements.py

The random numbers in `ThresholdMeasurement` with `use_torontonian=True` was not using the random number generator from config. This has been fixed in this patch.

fix(gaussian): Seeding `ThresholdMeasurement`+`use_torontonian`

---

README.md
benchmarks/conftest.py
benchmarks/gaussian_boson_sampling_benchmark.py
benchmarks/gaussian_homodyne_benchmark.py
benchmarks/gaussian_threshold_detection_benchmark.py
benchmarks/purefock_beamsplitter_benchmark.py
benchmarks/purefock_beamsplitter_increasing_cutoff_benchmark.py
benchmarks/purefock_beamsplitter_increasing_modes_benchmark.py
benchmarks/purefock_boson_sampling_benchmark.py
benchmarks/purefock_general_benchmark.py
benchmarks/purefock_interferometer_benchmark.py
benchmarks/purefock_interferometer_increasing_modes_benchmark.py
benchmarks/purefock_squeezing_increasing_cutoff_benchmark.py
benchmarks/purefock_squeezing_increasing_modes_benchmark.py
benchmarks/tf_1_mode_cvnn_benchmark.py
benchmarks/tf_cvnn_benchmark.py
benchmarks/tf_general_benchmark.py
benchmarks/tf_purefock_displacement_benchmark.py
pyproject.toml

Strawberry Fields has not been updated for a while, and it fails with recent version of SciPy (e.g., with strawberryfields==0.23.0 and scipy==1.14.0). For this reason, the strawberryfields imports from `benchmarks` were moved to a pytest fixture. In `scripts` this has not been done, since these files don't use pytest, and have less rationale in running these without strawberryfields.

chore: Remove strawberryfields from benchmark dependencies

---

tests/test_cvqnn.py

Since f3023f343b2ed642f4b8936f5d338d8026356f84, some tests are flaky, since the state is not automatically normalized after applying active gates, making this test flaky. To remedy this situation, the Fock space cutoff is increased.
Similar fix was done in 88521afbee23554c3a30d39c57eb93a2e16aaf24, but that was not comprehensive enough.

chore(tests): Fix flaky test in `test_cvqnn.py` again

---

piquasso/_math/hafnian/__init__.py
piquasso/_math/hafnian/loop_corrections.py
piquasso/_math/hafnian/loop_hafnian.py
piquasso/_math/hafnian/plain_hafnian.py
piquasso/_math/hafnian/powtrace.py
piquasso/_math/hafnian/utils.py
scripts/hafnian_benchmark.py
scripts/loop_hafnian_benchmark.py
tests/_math/test_hafnian.py

The `hafnian` and `loop_hafnian` functions were rewritten to account for multiplicities, according to https://arxiv.org/abs/2108.01622.
The tests in `test_hafnian.py` were rewritten accordingly. Two benchmarks are included in `scripts`.
Source: https://arxiv.org/abs/2108.01622

perf(hafnian): Include repetitions

---

piquasso/api/simulator.py
tests/api/conftest.py

We should prevent users to write `Simulator` classes which uses the `BaseCalculator`, since `BaseCalculator` implements nothing.

fix(api): Deleting `_default_calculator_class` initial value

---

CMakeLists.txt
piquasso/_math/CMakeLists.txt
piquasso/_math/linalg.py
piquasso/_math/torontonian.cpp
piquasso/_simulators/gaussian/calculations.py
piquasso/_simulators/gaussian/probabilities.py
piquasso/_simulators/gaussian/state.py
scripts/loop_torontonian_benchmark.py
src/CMakeLists.txt
src/loop_torontonian.cpp
src/loop_torontonian.hpp
src/matrix.hpp
src/numpy_utils.hpp
src/torontonian_common.cpp
src/torontonian_common.hpp
tests/_math/test_torontonian.py
tests/_simulators/gaussian/test_measurements.py
tests/_simulators/gaussian/test_state.py
tests/conftest.py

The loop torontonian is implemented according to
https://arxiv.org/abs/2202.04600 and https://arxiv.org/abs/2109.04528.

feat(gaussian): Loop torontonian implementation

---

piquasso/_simulators/fock/calculations.py
piquasso/_simulators/fock/general/state.py
piquasso/_simulators/fock/pure/batch_state.py
piquasso/_simulators/fock/pure/calculations/homodyne.py
piquasso/_simulators/fock/pure/state.py
piquasso/_simulators/fock/state.py
piquasso/_simulators/gaussian/calculations.py
piquasso/_simulators/gaussian/state.py
piquasso/_simulators/sampling/calculations.py
piquasso/_simulators/sampling/state.py
piquasso/api/config.py
tests/_simulators/fock/general/test_state.py
tests/_simulators/fock/pure/test_batch.py
tests/_simulators/fock/pure/test_state.py
tests/_simulators/gaussian/test_state.py
tests/_simulators/sampling/test_preparations.py
tests/api/test_config.py

In `Config`, a `validate` boolean flag is defined to enable users to turn off some validations during the simulation.
This may be useful for 2 reasons:
- Sometimes the validations are slow (e.g., `FockState.validate`) and unnecessary. Turning off validations could yield a slight performance increase in some cases.
- Disabling validations with TensorFlow or JAX can be useful, since some validations often cannot be compiled using XLA. It would be a win-win situation if one could validate user input while not hindering XLA compilation.

feat(config): `validate` flag

---

piquasso/_simulators/connectors/jax_/connector.py
piquasso/_simulators/connectors/numpy_/connector.py
piquasso/_simulators/connectors/tensorflow_/connector.py
piquasso/api/connector.py
tests/api/conftest.py
tests/api/test_connector.py

`BaseConnector` was not abstact before, one could technically instantiate it, but basically all methods raise a `NotImplementedError`. This is wrong, since in theory if there is a plugin writing a custom `BaseConnector`, simulations could fail between minor versions, since we can't guarantee that we won't start using a connector method in a calculation not used before.

feat!(api): Make `BaseConnector` abstract

---

tox.ini

The notebook `cvqnn-with-tensorflow.ipynb` testing is very slow, therefore it is best to ignore it in `tox`.

chore(tox): Ignoring `cvqnn-with-tensorflow.ipynb`

---

piquasso/_simulators/fock/general/state.py
piquasso/_simulators/fock/pure/batch_state.py
piquasso/_simulators/fock/pure/state.py
piquasso/api/config.py
piquasso/api/connector.py
piquasso/api/instruction.py
piquasso/api/program.py
piquasso/api/result.py
piquasso/api/simulator.py
piquasso/api/state.py
tests/_simulators/sampling/test_measurements.py
tests/_simulators/sampling/test_preparations.py
tests/api/test_connector.py
tests/api/test_result.py
tests/api/test_simulator.py
tests/api/test_state.py
tests/instructions/test_str.py

The `__repr__` methods got updated and added in some cases, where it wasn't available. I tried to make it consistently of the form of `SomeClass(param=param)`. In `*FockState` classes, I reserved the original definition for `__str__`.

chore!: Added/updated `__repr__` methods

---

piquasso/instructions/gates.py

The classes `_PassiveLinearGate` and `_ActiveLinearGate` has been made abstract, because they are not supposed to be instantiated.

refact: Make `_*LinearGate` abstract

---

piquasso/_math/combinatorics.py
piquasso/_math/fock.py
piquasso/_simulators/fock/calculations.py
piquasso/_simulators/fock/general/state.py
piquasso/_simulators/fock/pure/state.py
piquasso/_simulators/sampling/state.py
scripts/profile_cvnn_layer.py
scripts/profile_cvnn_layer_batch.py
tests/_math/test_torontonian.py

The logic for the function `get_fock_space_basis` got rewritten to reuse allocated memory and calculate array sizes in advance. For this, some functions in `fock.py` got JITted. Moreover, the utility function `cutoff_cardinality` got renamed to `cutoff_fock_space_dim` being a more fitting name. Moreover, `powerset` got deleted from the production code, since it is not used anymore.

perf: Rewrite `get_fock_space_basis`

---

benchmarks/purefock_interferometer_increasing_modes_benchmark.py
piquasso/_math/indices.py
piquasso/_simulators/connectors/numpy_/interferometer.py
piquasso/_simulators/fock/calculations.py

There are several functions in calculations used by `*FockSimulator` classes, that are used to calculate indices. These are rewritten using Numba for better performance.

perf(fock): JITting utility functions

---

scripts/loop_torontonian_benchmark.py
scripts/torontonian_benchmark.py
src/CMakeLists.txt
src/loop_torontonian.cpp
src/torontonian.cpp

There seems to be a too big OMP overhead in the torontonian calculations, at least for smaller system sizes. It could be solved by coming up with a smarter schedule. For now, OMP is deleted from the code.
Moreover, some related benchmarks got updated.

perf: Delete OMP in torontonian calculations

---

piquasso/_math/linalg.py
piquasso/_math/permanent.py
piquasso/_simulators/sampling/calculations.py
piquasso/_simulators/sampling/utils.py
pyproject.toml
scripts/boson_sampling_benchmark.py
scripts/boson_sampling_hist.py
scripts/permanent_benchmark.py
tests/_math/test_permanent.py
tests/_simulators/sampling/test_measurements.py
tests/conftest.py

The classical simulation of Boson Sampling is implemented with a rudimentary algorithm, but it got reimplemented using the Clifford&Clifford algorithm B, see https://arxiv.org/abs/1706.01260.
Moreover, the implementation for the repeated BB/FG formula with n-ary Gray code has been copied from PiquassoBoost.
Additional tests were written for the permanent, and additional scripts were written for both the permanent and for BS as well. In `boson_sampling_benchmark.py`, Piquasso is compared with Perceval in BS.
Some seeded tests in `tests/_simulators/sampling` had to be modified  due to the modification of the sampling algorithm.

perf(sampling): Enhance classical BS simulation

---

piquasso/_math/permanent.py

The precision of the row and column repetitions are increased, since the variable `idx_max` can encounter overflow for bigger matrices.

fix(permanent): int32 -> int64

---

piquasso/_simulators/connectors/connector.py
tests/fermionic/gaussian/test_state.py

The test
`test_get_majorana_monomial_expectation_value_random_with_possible_multiplicities` is flaky, because the schur decomposition in the pfaffian calculation got an empty matrix sometimes. The pfaffian function should return with 1.0 in this case, and this edge case has been added into `BuiltinConnector.pfaffian`.

fix(fermionic): Fix pfaffian function

---

piquasso/fermionic/__init__.py
piquasso/fermionic/gaussian/__init__.py
piquasso/fermionic/gaussian/_misc.py
piquasso/fermionic/gaussian/state.py
piquasso/fermionic/instructions.py
tests/fermionic/conftest.py
tests/fermionic/gaussian/test_state.py

The methods `density_matrix` and `get_majorana_monomial_expectation_value` were incorrect, but they have been fixed. This mishap might have been caused by different conventions, and also https://arxiv.org/pdf/2111.08343 gets some equations wrong I think.
The documentation has been extended for clarity.

fix(fermionic): Fixing density matrix calculation

---

piquasso/fermionic/__init__.py
piquasso/fermionic/gaussian/state.py
tests/fermionic/conftest.py
tests/fermionic/gaussian/test_state.py

The convention for the Majorana operators is changed so that we do not divide by `\sqrt{2}`. The covariance matrix stays the same up to a factor of `2`.

fix(fermionic): Change Majorana convention

---

.github/workflows/build.yml

A release stage has been added according to
https://cibuildwheel.pypa.io/en/stable/deliver-to-pypi/

chore: Add release stage

---

.github/workflows/build.yml
README.md
piquasso/_math/CMakeLists.txt

The Windows wheels have not been repaired by `cibuildwheel` by default, see https://cibuildwheel.pypa.io/en/1.x/options/#repair-wheel-command
According to the `cibuildwheel` documentation, this could be fixed by enabling `delvewheel`.
Moreover, the `*.pyd` files are installed to the proper location via setting `RUNTIME DESTINATION` in cmake.
Fixes #389

FIX(build.yml): Add Windows wheel repairing

---

.codecov.yml
piquasso/_math/decompositions.py
piquasso/_math/transformations.py
piquasso/_simulators/gaussian/state.py
piquasso/fermionic/gaussian/calculations.py
piquasso/fermionic/gaussian/state.py
tests/_math/test_torontonian.py
tests/fermionic/gaussian/test_state.py

Sometimes we need to switch between the xxpp and xpxp basis. In Piquasso, this is implemented by a basis changing matrix. However, as this matrix only reorders rows/columns, it would be much nicer if the vectors/matrices would just be reindexed. Therefore, this approach is deleted in favour of basis changing indices.

refact(_math): xpxp-xxpp basis changing rewritten

---

piquasso/instructions/gates.py
tests/_simulators/gaussian/test_state.py
tests/fermionic/gaussian/test_state.py

Tests have been added for Gaussian state density matrices verifying that the interferometer matrix parameter specified to `Interferometer` is the same unitary which acts on the 1-particle Hilbert spaces. Moreover, a minor error has been fixed in the docstrings.

test(gaussian): Adding density matrix test

---

docs/simulators/fock.rst

In the documentation, there is a warning providing information regarding the ordering of the Fock basis states. However, it is wrong, since the ordering in the particle number conserving subspace is anti-lexicographic, instead of lexicographic. This has been corrected in this patch.

fix(docs): Typo in ordering warning

---

.codecov.yml
piquasso/_math/combinatorics.py
piquasso/_simulators/connectors/_utils.py
piquasso/_simulators/connectors/jax_/connections.py
piquasso/_simulators/connectors/numpy_/connections.py
piquasso/_simulators/connectors/numpy_/connector.py
piquasso/fermionic/_utils.py

A Numba implementation of `calculate_interferometer_on_fermionic_fock_space` is added. The `_precalculate_passive_linear_indices` got simplified, renamed, and moved to `piquasso/_simulators/connectors/_utils.py`. A minor improvement in `comb` has been added by using the symmetry of the binomial coefficients. Finally, the function `get_fock_subspace_index_first_quantized` is also simplified using Pascal's rule.

perf(fermionic): Minor improvements

---

benchmarks/purefock_clements_interferometer_comparison_benchmark.py
piquasso/decompositions/clements.py
tests/decompositions/test_clements.py

The `clements` module is modified so that in the decompositions, the phaseshifters are not intertwined in the circuit, but moved to the end. This involves an extra step, which has been omitted before. However, this extra step yields a nicer decomposition.
In detail, previously Eq. (4) was implemented from https://arxiv.org/abs/1603.08788, but now Eq. (5) is used.

feat!(clements): Commuting phaseshifters to end

---

piquasso/_simulators/connectors/jax_/connector.py
tests/test_extras.py

Importing piquasso raised an `ImportError` when `jax` was not installed, due to a wrong import. This has been fixed in this patch, and tests are also included to test correct functioning without `tensorflow` or `jax`.

FIX: `jax` dependency fix

---

piquasso/fermionic/fock/state.py

We have encountered the following warning:
```
Encountered the use of a type that is scheduled for deprecation: type 'reflected list' found for argument 'occupation_numbers' of function 'get_fock_space_index'.
```
To fix this, one has to convert all inputs to arrays from lists.

fix: Numba reflected list warning

---

piquasso/fermionic/fock/state.py
tests/fermionic/fock/test_state.py

In the `fermonic` package, the method `PureFockState.fock_probabilities` returns with the particle number detection probabilities for a generic pure state written in the Fock basis. However, the corresponding occupation numbers are not returned, but the ordering explained in the [documentation](https://piquasso.readthedocs.io/en/v6.0.1/experimental/fermionic.html#piquasso.fermionic.gaussian.GaussianState.fock_probabilities). This might be inconvenient for users.
To remedy this, the `PureFockState.fock_probabilities_map` method (practically a property, as `fock_probabilities`) is implemented, which returns `fock_probabilities` "zipped" with the corresponding occupation numbers.
Closes #435.

feat(fermionic): `PureFockState.fock_probabilities_map`

---

piquasso/_simulators/fock/state.py
piquasso/_simulators/gaussian/state.py
tests/_simulators/fock/general/test_state.py
tests/_simulators/fock/pure/test_state.py
tests/_simulators/gaussian/test_state.py

Resolves #436 
- Implemented a convenience method to obtain marginal particle number probabilities. The method calls `reduced` internally and returns `fock_probabilities` for the selected subsystem
- Added unit tests confirming that the new method gives the same results as reducing the state explicitly, covering Fock, PureFock, and Gaussian simulators

Add `get_marginal_fock_probabilities` method to Fock and Gaussian

---

tests/test_extras.py

During testing, the `help(piquasso)` is called, which - using the `-s` flag in `pytest` - prints out the entire help. Unfortunately, the pipeline uses this flag. To avoid printing it, just a simple `print` is called instead of `help`.

chore: Avoid printing unnecessary help in test logs

---

docs/conf.py
pyproject.toml

**Context:**
There are many copy snippets on the Piquasso documentation websites, and it would be nice to make them copyable.
Closes #463.
**Description of the Change:**
Adds the ``sphinx-copybutton`` extension and the requirement for the extension.
**Benefits:**
Every code snippet becomes copyable via a button that appears in the top-right corner of the snippet box.

Docs: add copybutton extension to docs

---

.github/workflows/tests.yml
pyproject.toml
tests/_math/test_decompositions.py
tests/_simulators/fock/pure/test_state.py
tests/_simulators/fock/test_gates.py
tests/_simulators/tensorflow/test_batch_gradient.py
tests/_simulators/tensorflow/test_connector.py
tests/_simulators/tensorflow/test_gates.py
tests/_simulators/tensorflow/test_gradient.py
tests/_simulators/tensorflow/test_measurements.py
tests/_simulators/test_simulator.py
tests/_simulators/test_simulator_equivalence.py
tests/conftest.py
tests/decompositions/test_clements.py
tests/slow/test_tf_function.py
tox.ini

Python 3.13 support is added in this patch.
It was a bit tricky, as TensorFlow is not released for Python 3.13 yet, so one has to disable all the tests that use TensorFlow on Python 3.13. This is done by creating a new `--skip-tensorflow` pytest option, which disables these tests. By putting the `tensorflow` import in a fixture, we can optionally skip those tests that try to use this fixture.
As there are many parametrized tests depending on `tensorflow` (e.g., through `TensorflowConnector`), we had to implement a mechanism to use fixtures in parametrized tests as parameters. This is enabled by the `pytest_lazy_fixtures` plugin.
The test `tests/_simulators/fock/pure/test_state.py::test_mean_position` mistakenly used `TensorflowConnector`, so this test has been rewritten to use the default …

chore: Add Python 3.13 support

---

piquasso/_math/permanent.cpp
piquasso/_math/pfaffian.cpp
piquasso/_math/torontonian.cpp
src/numpy_utils.hpp
tests/_math/test_permanent.py

The problem with the flag `py::array::forcecast` is that, e.g., in a scenario where the scalars in the input array has a dtype which is equivalent to `double` in C++, `pybind` will go through the signatures, and if the first signature is specified with `float` and `forcecast` is also specified, the `double`s will be converted to `float`s here, instead of checking the next signature. This results in a decrease in precision.
To resolve this, the `forcecast` flag is deleted. However, casting still needs to be done for integer array arguments, therefore the functions `numpy_to_matrix` and `numpy_to_vector` got extended with an additional template argument `Flags`.

fix(_math): Avoid forcecasting

---

piquasso/api/simulator.py
tests/api/test_simulator.py

Passing in the `initial_state` argument to the `Simulator.execute` method such that the simulator instance's `d` attribute does not match the shape of `initial_state` raises an undescriptive error. This is handled by raising an `InvalidState` error in such cases.
Resolves #464.

feat(api): Handling number of modes mismatch

---

piquasso/api/result.py
tests/_simulators/sampling/test_measurements.py

Adds the `Result.get_counts` method that depends on the `Result.samples` attribute.

Add `Result.get_counts`

---

CHANGELOG.md
README.md
piquasso/_simulators/gaussian/state.py

Fix minor typos in
- `CHANGELOG.md`
- `README.md`
- `piquasso/_simulators/gaussian/state.py`

fix(docs): correct typo

---

piquasso/instructions/gates.py

The non-singularity of the adjacency matrix in `Graph` is validated, although there is no reason for doing this in the current algorithm.

FIX(gaussian): Delete unnecessary singularity check in `Graph`
