Budapest-Quantum-Computing-Group/piquasso

- piquasso/_backends/gaussian/probabilities.py
- piquasso/_backends/gaussian/state.py
The `ThresholdMeasurement` using the torontonian is simplified, since
the GBS algorithm doesn't use the same `GaussianState._perform_sampling`
method anymore, since e9322042e857f8ae9293f5b87f216bb167afe55d.
> refact(GaussianState): Threshold simplification

- docs/tutorials/getting-started.ipynb
- docs/tutorials/separating-programs.ipynb
- piquasso/_backends/fock/state.py
- piquasso/_backends/gaussian/state.py
- piquasso/_math/fock.py
- piquasso/api/mode.py
- piquasso/api/program.py
- piquasso/api/simulator.py
- piquasso/api/state.py
- piquasso/instructions/channels.py
- piquasso/instructions/gates.py
- piquasso/instructions/measurements.py
- piquasso/instructions/preparations.py
- the following files have been affected:
modified:   docs/tutorials/getting-started.ipynb
modified:   docs/tutorials/separating-programs.ipynb
modified:   piquasso/_backends/fock/state.py
modified:   piquasso/_backends/gaussian/state.py
modified:   piquasso/_math/fock.py
modified:   piquasso/api/mode.py
modified:   piquasso/api/program.py
modified:   piquasso/api/simulator.py
modified:   piquasso/api/state.py
modified:   piquasso/instructions/channels.py
modified:   piquasso/instructions/gates.py
modified:   piquasso/instructions/measurements.py
mainly fixing typos, adding clarification whenever possible.
> Fixing Docstrings:

- piquasso/_backends/gaussian/state.py
- tests/backends/gaussian/test_state.py
- A new method called `variance_photon_number` has been
implemented in Gaussian state.
- A new test has been implemented for different cases.
> Feat(variance_photon_number) in `gaussian/state`:

- piquasso/_backends/fock/general/state.py
- piquasso/_backends/fock/pure/state.py
- piquasso/_backends/fock/state.py
- tests/backends/fock/general/test_state.py
- tests/backends/fock/pure/test_state.py
- tests/backends/fock/test_state.py
- the density matrix for the `PureFockState` has been fixed
- quadratuers_mean_variance has been implemented in the `fock\general\state.py`.
- test cases have been modified accordingly.
> fix(PureFockState) quadratures method:

- piquasso/_math/fock.py
When calculating the representation of the passive linear gates, the
`symmetric_tensorpower` method is used, which is terribly slow. To
improve this, for the calculation of the permanent, the
`RyserGuanPermanentCalculator` is used.
> perf(fock): Using `theboss`

- piquasso/_backends/fock/state.py
- tests/backends/fock/test_state.py
- tests/backends/test_backend_equivalence.py
The Wigner function in the `BaseFockState` class has been copyed from
QuTiP.
The Wigner function from the `BaseFockState` is compared to the result
from `GaussianState` in a test.
> feat(fock): Wigner function

- .github/ISSUE_TEMPLATE/issue_template.yaml
- Fixed a grammar mistake in the issue template
> fix grammar

- piquasso/_backends/fock/pure/calculations.py
Some gate implementation embedded the matrix into the larger Fock space,
then multiplied the state vector, which is quite inefficient. This is
rewritten to calculate the new vector coefficients directly, instead.
This will be done for the `general` Fock simulation and similar for the
passive gates as well.
> perf(fock/pure): Avoid embedding of active gates

- piquasso/_backends/fock/pure/calculations.py
Some gate implementation embedded the matrix into the larger Fock space,
then multiplied the state vector, which is quite inefficient. It is
already been rewritten for the active gates in commit
0f215746cf75eb0252120257792e851536eeb514, the passive gates are handled
in this patch.
Note, that `_apply_single_mode_representation_to_state` is rewritten to
work with multiple modes, hence the name
`_apply_subsystem_representation_to_state`.
This will be done for the `general` Fock simulation later.
> perf(fock/pure): Avoid embedding of passive gates

- .github/workflows/tests.yml
- README.md
- requirements.txt
- tox.ini
Support for Python3.10 has been added.
Packages in requirements.txt and README.md has been updated accordingly.
Closes #127
> Support for Python 3.10

- piquasso/_backends/fock/pure/calculations.py
**Problem**
Creating the interferometer was very costly due to indexing, and the algorithm calculating the matrix elements has been calculating these indices redundantly. This algorithm is further compicated by the fact that one has to search for the non-zero indices in a given occupation number, in order to acquire certain indices.
**Solution**
The algorithm has been optimized: the `get_index_in_fock_subspace` call for the column indices in the inner for loop is unnecessary, since it has been done for the row indices in the outer for loop, and can be reused. This way, the logic of the algorithm can be completely modified, as follows:
1. All the index calculations are done in a separate for loop, and is done only once for every block matrix corresponding to a given particle number.
2. …
> perf(purefock): Interferometer optimization

- piquasso/_backends/fock/pure/calculations.py
The Kerr gate calculation is more efficient by calculating it without an additional for loop. This showed great improvement in calculating its gradient as well.
> perf(fock): Kerr gate

- piquasso/_backends/fock/pure/calculations.py
The upstream differential in a custom gradient does not always have a value, but when it has, one can calculate using numpy.
The function `get_static_value` evaluates the `tensorflow` tensor if it is efficiently calculable, and we proceed with the calculation using `numpy` arrays. If it is not efficiently calculable (returns with `None`), we calculate using `tensorflow`.
> perf(tensorflow): Converting upstream to numpy

- piquasso/_backends/fock/pure/state.py
- tests/backends/fock/pure/test_state.py
- tests/backends/tensorflow/test_gradient.py
A method called `mean_position` has been written for `PureFockState`, which calculates the average position on the specified mode.
> feat(PureFockState): `mean_position`

- piquasso/_math/gradients.py
- tests/backends/tensorflow/test_gradient.py
While writing some tests testing the squeezing and displacement matrix gradients, I encountered an error in the squeezing gradient, which got fixed here.
> fix(_math/gradients): Squeezing gradient fix

- .flake8
- benchmarks/purefock_clements_interferometer_comparison_benchmark.py
- benchmarks/tf_purefock_displacement_benchmark.py
- piquasso/_backends/fock/general/calculations.py
- piquasso/_backends/fock/pure/calculations.py
- piquasso/_backends/gaussian/calculations.py
- piquasso/_backends/sampling/state.py
- piquasso/_math/fock.py
- piquasso/_math/hafnian.py
- piquasso/api/simulator.py
- requirements.txt
- scripts/cvnn_1_mode_gradient_comparison.py
- scripts/profile_cvnn_layer.py
- tests/_math/test_hafnian.py
- tests/api/test_simulator.py
- tests/backends/fock/general/test_gates.py
- tests/backends/fock/pure/test_gates.py
- tests/backends/fock/test_gates.py
- tests/backends/gaussian/test_preparations.py
- tests/backends/gaussian/test_state.py
- tests/backends/tensorflow/test_gradient.py
- tests/decompositions/test_clements.py
The files were reformatted accordingly.
> dev: Upgrade `flake8` and `black`

- piquasso/_backends/gaussian/state.py
- tests/backends/gaussian/test_state.py
A method called `GaussianState.purify` has been implemented, which returns with the purification of the `GaussianState` instance.
> feat(gaussian): `GaussianState.purify`

- piquasso/_backends/fock/pure/calculations.py
Some indexing has been moved outside of the for loop to improve performance.
Moreover, if the upstream is static valued, then we calculate with numpy,
meaning that we don't need to pad the matrices, since in numpy we can do item
assignments.
Finally, some caching has been added to some index calculation functions.
> perf(tensorflow): Interferometer gradient

- piquasso/__init__.py
- piquasso/_backends/fock/pure/batch_state.py
- piquasso/_backends/fock/pure/calculations.py
- piquasso/_backends/fock/pure/simulator.py
- piquasso/_backends/fock/pure/state.py
- piquasso/_math/fock.py
- piquasso/api/instruction.py
- piquasso/api/simulator.py
- piquasso/instructions/batch.py
- scripts/profile_cvnn_layer_batch.py
- tests/backends/fock/pure/test_batch.py
- tests/backends/tensorflow/test_batch_gradient.py
The batch processing of pure Fock states has been implemented. This is done by storing multiple states in a tensor of shape `(state_vector_size, number_of_batches)` in `BatchPureFockState`. However, `BatchPureFockState` has a limited support of methods compared to the original `PureFockState`.
> feat: Batch processing of pure Fock states

- piquasso/_backends/fock/pure/calculations/__init__.py
- piquasso/_backends/fock/pure/calculations/passive_linear.py
The passive linear gates got extracted, because `calculations.py` got too large.
> refact(fock/pure): Extract passive linear gates

- piquasso/_backends/fock/pure/calculations/passive_linear.py
Some typing errors have been fixed. The typing has to be consistent, especially when calculating with tensorflow.
> fix(fock/pure): Fix interferometer typing

- piquasso/_backends/calculator.py
- piquasso/_backends/fock/calculations.py
- piquasso/_backends/fock/general/calculations.py
- piquasso/_backends/fock/pure/calculations/passive_linear.py
- piquasso/_math/fock.py
- piquasso/api/calculator.py
- tests/api/test_calculator.py
Passive calculations in `FockSimulator` got rewritten in a way that passive calculations are written in `PureFockSimulator`.
> perf(fock): Passive calculations

- piquasso/_math/fock.py
- piquasso/_math/gate_matrices.py
The calculation of the squeezing and displacement matrices got vectorized. It does not yield any noticable performance improvement, but when generalizing these functions in the future to be able to compute with tensorflow, it will be faster, since this implementation uses less tensorflow operations.
> perf(fock): Rewrite gate matrix calculation

- .codecov.yml
- .github/workflows/tests.yml
The Codecov uploading is flaky, and maybe an update will solve this.
> chore(.github): Update codecov action

- benchmarks/tf_1_mode_cvnn_benchmark.py
- piquasso/_backends/fock/pure/batch_state.py
- piquasso/_backends/fock/pure/calculations/__init__.py
- piquasso/_backends/fock/pure/calculations/passive_linear.py
- piquasso/_backends/fock/pure/state.py
- scripts/cvnn_1_mode_gradient_comparison.py
- scripts/cvnn_state_learning_benchmark.py
- scripts/profile_cvnn_layer.py
- tests/backends/fock/pure/test_batch.py
- tests/backends/tensorflow/test_gradient.py
- tests/test_cvqnn.py
`PureFockState._state_vector` has been used in tests, but has not been made officially public by removing the leading underscore.
> feat(fock/pure): Making `_state_vector` public

- piquasso/_backends/fock/general/state.py
- piquasso/_backends/fock/pure/state.py
- piquasso/_backends/fock/state.py
- tests/backends/fock/pure/test_state.py
- tests/backends/fock/test_state.py
The `get_purity` method is implemented for `(Pure)FockState`.
> feat(fock): `get_purity`

- docs/index.rst
- docs/instructions/misc.rst
- piquasso/__init__.py
- piquasso/_backends/fock/pure/calculations/__init__.py
- piquasso/_backends/fock/pure/calculations/misc.py
- piquasso/_backends/fock/pure/calculations/utils.py
- piquasso/_backends/fock/pure/simulator.py
- piquasso/instructions/misc.py
- tests/backends/fock/pure/test_misc.py
The ability to specify postselection has been added.
> feat(fock/pure): `PostSelectPhotons`

- piquasso/__init__.py
- piquasso/_backends/fock/pure/calculations/__init__.py
- piquasso/_backends/fock/pure/calculations/measurements.py
- piquasso/_backends/fock/pure/simulator.py
- piquasso/instructions/measurements.py
- tests/backends/fock/pure/test_measurements.py
- tests/backends/tensorflow/test_measurements.py
Support for postselecting with imperfect particle-resolving photon detectors has been added.
> feat(fock): `ImperfectPostSelectPhotons`

- piquasso/_backends/sampling/calculations.py
- piquasso/_backends/sampling/simulator.py
- tests/backends/sampling/test_measurements.py
- tests/backends/test_backend_equivalence.py
Post-selection in `SamplingSimulator` has been implemented. An equivalence test has been written to cross-check the results with `PureFockSimulator`.
> feat(sampling): Post-selection in `SamplingSimulator`

- .codecov.yml
- benchmarks/conftest.py
- benchmarks/purefock_homodyne_benchmark.py
- piquasso/_backends/fock/pure/calculations/__init__.py
- piquasso/_backends/fock/pure/calculations/homodyne.py
- piquasso/_backends/fock/pure/simulator.py
- piquasso/api/result.py
- tests/backends/fock/pure/test_measurements.py
The algorithm for homodyne sampling in the `PureFockSimulator` has been implemented using Numba. The implemented algorithm uses inverse transform sampling along with mode-by-mode sampling.
> feat(fock): Homodyne measurement

- piquasso/_backends/fock/pure/state.py
- tests/backends/fock/pure/test_state.py
The photon number variance has been implemented in `PureFockState`.
> feat(fock/pure): Photon number variance

- piquasso/_backends/gaussian/state.py
- tests/backends/gaussian/test_state.py
A method is implemented for calculating the probabilities corresponding to threshold particle number measurement.
> feat(gaussian): `get_threshold_detection_probability`

- .github/workflows/tests.yml
- README.md
- docs/tutorials/cvqnn-with-tensorflow.ipynb
- docs/tutorials/jax-example.ipynb
- piquasso/_math/gate_matrices.py
- piquasso/api/calculator.py
- tox.ini
Tests for Python 3.12 are added in this patch.
> chore: Adding Python 3.12 tests

- docs/api/exceptions.rst
- docs/api/simulator.rst
- docs/simulators/fock.rst
- docs/simulators/gaussian.rst
- docs/simulators/sampling.rst
- docs/states/fock.rst
- piquasso/_simulators/fock/state.py
- piquasso/api/calculator.py
- piquasso/api/simulator.py
Some links and wording got corrected in this patch. Moreover, the inheritance and inherited members are displayed where applicable.
> docs: Update and fix documentation

- CMakeLists.txt
- pyproject.toml
- scripts/torontonian_benchmark.py
- src/CMakeLists.txt
- src/torontonian.cpp
Parallelization of the torontonian calculation has been added. Moreover, a benchmark script has been written to compare it with the `thewalrus` implementation.
> perf(torontonian): Parallelization + benchmark script

- docs/advanced/decompositions.rst
- docs/index.rst
- piquasso/decompositions/clements.py
- tests/conftest.py
- tests/decompositions/test_clements.py
The decomposition was tricky to use before, because one had to implement the circuit manually. `instructions_from_decomposition` is created to compile the instructions to be applied to the program.
Moreover, the documentation got updated and exposed in the 'Advanced' section in the documentation.
> feat(clements): Helper function for using decomposition

- piquasso/_simulators/fock/pure/calculations/passive_linear.py
- tests/_simulators/fock/pure/test_gradient.py
The custom gradient `_calculate_interferometer_gradient_on_fock_space` is be partially JIT-compiled using Numba.
> perf(fock): Interferometer custom gradient JITted

- scripts/probability_loss_comparison.py
The loss of probabilities due to the Fock space truncation is compared in this script.
> scripts: Probability loss comparison script

- piquasso/_math/jax/hafnian.py
- piquasso/_math/jax/utils.py
- piquasso/_math/linalg.py
- piquasso/_simulators/connectors/jax_/connector.py
- piquasso/_simulators/gaussian/probabilities.py
- piquasso/_simulators/gaussian/state.py
- piquasso/api/connector.py
- tests/_math/test_hafnian.py
- tests/_simulators/gaussian/test_gradient.py
A differentiable loop hafnian implementation is provided in `JaxConnector`, making some extra methods in `GaussianState` differentiable, e.g., `get_particle_detection_probability`.
> feat(gaussian): Differentiable loop hafnian

- piquasso/_math/jax/hafnian.py
The remaining loops in the loop hafnian calculation were rewritten using JAX `fori_loop`. For this, the for loops are rewritten to be statically sized using masks.
> perf(jax): Loop hafnian compilation speedup

- scripts/cvqnn_state_learning_benchmark.py
- scripts/cvqnn_tensorflow_comparison_benchmark.py
- scripts/hafnian_benchmark.py
- scripts/loop_hafnian_benchmark.py
- scripts/probability_loss_comparison.py
Some scripts default parameters got updated, and
`cvqnn_state_learning_benchmark.py` is repurposed.
> scripts: Update CVQNN scripts

- tests/_simulators/sampling/test_jax_gradient.py
Testing of `SamplingSimulator` with `JaxConnector` is extended.
> test(sampling): Testing gradient for multiphoton setup

- piquasso/_math/indices.py
- piquasso/_simulators/connectors/connector.py
- piquasso/fermionic/gaussian/calculations.py
- tests/fermionic/gaussian/test_gates.py
`GaussianSimulator` has been extended with the ability to handle `GaussianHamiltonian` with `modes` specified. This solution is a bit lazy as it is done by embedding, but it can be improved later if needed.
> feat(fermionic): `GaussianHamiltonian` on subsystem

- piquasso/fermionic/fock/calculations.py
- piquasso/fermionic/fock/simulator.py
- piquasso/fermionic/gaussian/calculations.py
- piquasso/fermionic/gaussian/simulator.py
- piquasso/instructions/gates.py
- tests/fermionic/fock/test_gates.py
- tests/fermionic/gaussian/test_gates.py
- tests/fermionic/test_simulator_equivalence.py
The analog of `Squeezing2` for the fermonic package has been implemented for both `GaussianSimulator` and `PureFockSimulator`.
> feat(fermionic): `Squeezing2`

- .codecov.yml
- piquasso/fermionic/__init__.py
- piquasso/fermionic/fock/_utils.py
- piquasso/fermionic/fock/calculations.py
- piquasso/fermionic/fock/simulator.py
- piquasso/fermionic/instructions.py
- tests/fermionic/fock/test_gates.py
The `ControlledPhase` gate has been implemented for `fermionic.PureFockSimulator`.
> feat(fermionic): `ControlledPhase`

- pyproject.toml
The `pyproject.toml` file got updated.
> chore: Update `pyproject.toml`

- piquasso/fermionic/__init__.py
- piquasso/fermionic/fock/_utils.py
- piquasso/fermionic/fock/calculations.py
- piquasso/fermionic/fock/simulator.py
- piquasso/fermionic/gaussian/calculations.py
- piquasso/fermionic/gaussian/simulator.py
- piquasso/fermionic/instructions.py
- tests/fermionic/fock/test_gates.py
- tests/fermionic/test_simulator_equivalence.py
The `IsingXX` gate has been implemented in both `PureFockSimulator` and `GaussianSimulator`.
> feat(fermionic): Ising XX coupling gate

- docs/bibliography.bib
- docs/tutorials/dense-subgraph-gbs.ipynb
- docs/tutorials/index.rst
A new tutorial has been added, which introduces a heuristic algorithm for finding dense k-subgraphs using GBS.
> docs(tutorials): Finding dense k-subgraphs with GBS
